# Generated by Django 6.0.6 on 2026-07-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
